package org.main;
// Generated 7 sept. 2019 16:10:03 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Jeux generated by hbm2java
 */
public class Jeux  implements java.io.Serializable {


     private Integer idGame;
     private String title;
     private String description;
     private Date dateAchat;

    public Jeux() {
    }

    public Jeux(String title, String description, Date dateAchat) {
       this.title = title;
       this.description = description;
       this.dateAchat = dateAchat;
    }
   
    public Integer getIdGame() {
        return this.idGame;
    }
    
    public void setIdGame(Integer idGame) {
        this.idGame = idGame;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDateAchat() {
        return this.dateAchat;
    }
    
    public void setDateAchat(Date dateAchat) {
        this.dateAchat = dateAchat;
    }




}


